# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'logClassifier.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_logClassifier(object):
    def setupUi(self, logClassifier):
        logClassifier.setObjectName("logClassifier")
        logClassifier.setWindowModality(QtCore.Qt.ApplicationModal)
        logClassifier.resize(230, 249)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(logClassifier.sizePolicy().hasHeightForWidth())
        logClassifier.setSizePolicy(sizePolicy)
        self.tabWidget = QtWidgets.QTabWidget(logClassifier)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 221, 231))
        self.tabWidget.setObjectName("tabWidget")
        self.competition = QtWidgets.QWidget()
        self.competition.setObjectName("competition")
        self.compKey = QtWidgets.QLineEdit(self.competition)
        self.compKey.setGeometry(QtCore.QRect(100, 10, 101, 31))
        self.compKey.setObjectName("compKey")
        self.matchNum = QtWidgets.QSpinBox(self.competition)
        self.matchNum.setGeometry(QtCore.QRect(100, 91, 101, 31))
        self.matchNum.setObjectName("matchNum")
        self.matchType = QtWidgets.QComboBox(self.competition)
        self.matchType.setGeometry(QtCore.QRect(100, 50, 101, 31))
        self.matchType.setObjectName("matchType")
        self.matchType.addItem("")
        self.matchType.addItem("")
        self.matchType.addItem("")
        self.matchType.addItem("")
        self.matchType.addItem("")
        self.compLabel = QtWidgets.QLabel(self.competition)
        self.compLabel.setGeometry(QtCore.QRect(10, 20, 91, 16))
        self.compLabel.setObjectName("compLabel")
        self.matchLabel = QtWidgets.QLabel(self.competition)
        self.matchLabel.setGeometry(QtCore.QRect(10, 60, 71, 16))
        self.matchLabel.setObjectName("matchLabel")
        self.matchNumLabel = QtWidgets.QLabel(self.competition)
        self.matchNumLabel.setGeometry(QtCore.QRect(10, 100, 81, 16))
        self.matchNumLabel.setObjectName("matchNumLabel")
        self.compCancel = QtWidgets.QPushButton(self.competition)
        self.compCancel.setGeometry(QtCore.QRect(10, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compCancel.setFont(font)
        self.compCancel.setObjectName("compCancel")
        self.compSubmit = QtWidgets.QPushButton(self.competition)
        self.compSubmit.setGeometry(QtCore.QRect(110, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.compSubmit.setFont(font)
        self.compSubmit.setObjectName("compSubmit")
        self.tabWidget.addTab(self.competition, "")
        self.practice = QtWidgets.QWidget()
        self.practice.setObjectName("practice")
        self.practiceTime = QtWidgets.QDateTimeEdit(self.practice)
        self.practiceTime.setGeometry(QtCore.QRect(10, 10, 194, 81))
        self.practiceTime.setObjectName("practiceTime")
        self.practiceCancel = QtWidgets.QPushButton(self.practice)
        self.practiceCancel.setGeometry(QtCore.QRect(10, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.practiceCancel.setFont(font)
        self.practiceCancel.setObjectName("practiceCancel")
        self.practiceSubmit = QtWidgets.QPushButton(self.practice)
        self.practiceSubmit.setGeometry(QtCore.QRect(110, 130, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.practiceSubmit.setFont(font)
        self.practiceSubmit.setObjectName("practiceSubmit")
        self.tabWidget.addTab(self.practice, "")

        self.retranslateUi(logClassifier)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(logClassifier)

    def retranslateUi(self, logClassifier):
        _translate = QtCore.QCoreApplication.translate
        logClassifier.setWindowTitle(_translate("logClassifier", "Log Classifier"))
        self.matchType.setCurrentText(_translate("logClassifier", "Qual"))
        self.matchType.setItemText(0, _translate("logClassifier", "Prac"))
        self.matchType.setItemText(1, _translate("logClassifier", "Qual"))
        self.matchType.setItemText(2, _translate("logClassifier", "QF"))
        self.matchType.setItemText(3, _translate("logClassifier", "SF"))
        self.matchType.setItemText(4, _translate("logClassifier", "F"))
        self.compLabel.setText(_translate("logClassifier", "Competition Key"))
        self.matchLabel.setText(_translate("logClassifier", "Match Type"))
        self.matchNumLabel.setText(_translate("logClassifier", "Match Number"))
        self.compCancel.setText(_translate("logClassifier", "Cancel"))
        self.compSubmit.setText(_translate("logClassifier", "Submit "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.competition), _translate("logClassifier", "Competition"))
        self.practiceCancel.setText(_translate("logClassifier", "Cancel"))
        self.practiceSubmit.setText(_translate("logClassifier", "Submit "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.practice), _translate("logClassifier", "Practice"))

